apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: consumerqpid
  name: consumerqpid
spec:
  volumes:
  - name: "conspy"
    hostPath:
      path: "/home/vagrant/FuseESB_proto/manifest/apache-qpid-proton/consumer.py"
  containers:
  - image: qpid-python
    imagePullPolicy: Never
    volumeMounts:
    - mountPath: "/home/consumer.py"
      name: "conspy"
    name: qpid-python
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
