apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: producerqpid
  name: producerqpid
spec:
  volumes:
  - name: "prodpy"
    hostPath:
      path: "/home/vagrant/FuseESB_proto/manifest/apache-qpid-proton/producer.py"
  containers:
  - image: qpid-python
    imagePullPolicy: Never
    volumeMounts:
    - mountPath: "/home/producer.py"
      name: "prodpy"
    name: qpid-python
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
