---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/iconUrl: img/icons/camel.svg
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
    labels:
      expose: "true"
      app: fuse75-spring-boot-camel-amq
      provider: fabric8
      version: 1.0-SNAPSHOT
      group: org.example.fis
    name: fuse75-spring-boot-camel-amq
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: fuse75-spring-boot-camel-amq
      provider: fabric8
      group: org.example.fis
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      fabric8.io/iconUrl: img/icons/camel.svg
      fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=fuse75-spring-boot-camel-amq&var-version=1.0-SNAPSHOT
    labels:
      app: fuse75-spring-boot-camel-amq
      provider: fabric8
      version: 1.0-SNAPSHOT
      group: org.example.fis
    name: fuse75-spring-boot-camel-amq
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: fuse75-spring-boot-camel-amq
        provider: fabric8
        group: org.example.fis
    template:
      metadata:
        annotations:
          fabric8.io/iconUrl: img/icons/camel.svg
          fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=fuse75-spring-boot-camel-amq&var-version=1.0-SNAPSHOT
        labels:
          app: fuse75-spring-boot-camel-amq
          provider: fabric8
          version: 1.0-SNAPSHOT
          group: org.example.fis
      spec:
        containers:
        - image: fis/fuse75-spring-boot-camel-amq:latest
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 180
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: "1.0"
              memory: 256Mi
            requests:
              cpu: "0.2"
              memory: 256Mi
          securityContext:
            privileged: false

